### ISSUE TITLE
Message 'Save As' NoReverseMatch

### ISSUE THREAD

**Issue by rjperez94** [jazzband/django-newsletter#322]
NoReverseMatch at /admin/newsletter/message/1/change/
Reverse for 'newsletter_message_preview' with arguments '('',)' not found. 1 pattern(s) tried: ['admin/newsletter/message/(.+)/preview/$']

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/newsletter/message/1/change/
Django Version: 2.2.12
Exception Type: NoReverseMatch
Exception Value: Reverse for 'newsletter_message_preview' with arguments '('',)' not found. 1 pattern(s) tried: ['admin/newsletter/message/(.+)/preview/$']
Exception Location: C:\Program Files\Python37\lib\site-packages\django\urls\resolvers.py in _reverse_with_prefix, line 673
Python Version: C:\Program Files\Python37\python.exe
Python Version: 3.7.6

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'newsletter',
]

This project of mine is from the tutorial project on the Django site

**Comment by frennkie** [comment]
The same problem happens in the Submission admin:

```
django.urls.exceptions.NoReverseMatch: Reverse for 'newsletter_submission_submit' with arguments '('',)' not found. 1 pattern(s) tried: ['admin\\/newsletter\\/submission\\/(.+)/submit/$']
```

This is triggered when there is not new object (e.g. because of a validation error). The template then tries to lookup a link (either `preview` for `Message` or submit for `Subscription` and fails.
