### ISSUE TITLE
Add RTD webhook

### ISSUE THREAD

**Issue by dokterbob** [jazzband/django-newsletter#353]
As I don't seem to have access to the settings anymore, I'm not able to update the RTD webhook.

I've generated a webhook URL `readthedocs.org/api/v2/webhook/django-newsletter/138554/` to be set up according to https://docs.readthedocs.io/en/stable/webhooks.html#github

**Comment by dokterbob** [comment]
Alternatively, I would *really* appreciate being able to change setting again.

**Comment by jezdez** [comment]
This should be fixed, I just had to resync the webhook from RTD, so no worries opening this ticket.

I'l reply to your question regarding getting settings permissions again in #343 for record keeping. Thanks!
