### ISSUE TITLE
TinyMCE widget not appearing, missing configs?

### ISSUE THREAD

**Issue by mradamcox** [jazzband/django-newsletter#385]
Hello and thanks for this nice project! I'm just getting started with it and so far everything has been straightforward, but...

I would like to use a rich text editor for creating my messages, and I'm having trouble getting it to show up in my admin interface.

I have

1. installed `django-tinymce` 3.5.0 (also tried 3.3.0 which I had in my project already)
2. added `tinymce` to `INSTALLED_APPS`
3. added the proper urls
4. set `NEWSLETTER_RICHTEXT_WIDGET = "tinymce.widgets.TinyMCE"`

I then created a new newsletter and began to create a new message. However, the text widget is still the default:
![image](https://user-images.githubusercontent.com/10427268/211600123-30977fec-729b-4e89-8d63-8c316b7fc0c5.png)

Is there a configuration step I'm missing?

I am using Django 2.2.20 (this is an upstream dependency) and Python 3.8.

**Comment by krj29b** [comment]
I've got the same problem.  Any hints?

Python 3.8, 3.10
django-newsletter==0.9.1
django-tinymce==3.5.0

**Comment by mradamcox** [comment]
No updates on my end. What version of Django are you using?

**Comment by krj29b** [comment]
Django==3.2

**Comment by ibtsam3301** [comment]
works for me on
Django==3.2
django-newsletter==0.9.1
django-tinymce==3.5.0

and

Python 3.10.6

**Comment by mradamcox** [comment]
I'm in the process of upgrading a number of libraries in my own app, and have checked back on this widget.

My old environment where the widget doesn't appear has
```
django==2.2.20
django-tinymce==3.3.0
django-newsletter==0.9.1
```
(and a lot of other packages). After upgrading to
```
django==3.2.18
django-tinymce==3.6.1
django-newsletter==0.9.1
```
The widget shows up as expected.

@krj29b if you are still having trouble with this and can provide more info, we can keep the ticket open, otherwise I'll chalk it up to the old DJango version (or something that had come along with it) and we can close.

**Comment by krj29b** [comment]
Thank you for your response. On my end, I solved the problem by writing a new Django application that imports the latest version of TinyMCE.

**Comment by mradamcox** [comment]
Sounds good, closing.
